import type {
  EntitiesResponse,
  MetricsResponse,
  SettingsResponse,
  TableResponse,
  WorkspaceOverview,
} from "@/lib/agentos-types";

export const fallbackOverview: WorkspaceOverview = {
  workspace: {
    id: "mx-agent",
    name: "MX AgentOS",
    status: "active",
    plan: "local",
    endpoint_url: "http://localhost:8000",
  },
  user: {
    name: "MX Operator",
    initials: "MX",
    email: "operator@mx.local",
  },
  navigation: [
    { label: "Home", href: "/", icon: "home", group: "main" },
    { label: "Chat", href: "/chat", icon: "message-square", group: "main" },
    { label: "Sessions", href: "/sessions", icon: "play", group: "main" },
    { label: "Traces", href: "/traces", icon: "list-tree", group: "main" },
    { label: "Studio", href: "/studio", icon: "layout-grid", group: "studio" },
    { label: "Learning", href: "/learning", icon: "brain", group: "learning" },
    { label: "Memory", href: "/memory", icon: "database", group: "main" },
    { label: "Knowledge", href: "/knowledge", icon: "book-open", group: "main" },
    { label: "Metrics", href: "/metrics", icon: "chart-no-axes-column", group: "main" },
    { label: "Evaluation", href: "/evaluation", icon: "clipboard-check", group: "main" },
    { label: "Approvals", href: "/approvals", icon: "square-check", group: "main" },
    { label: "Scheduler", href: "/scheduler", icon: "calendar-clock", group: "main" },
    { label: "Settings", href: "/settings/profile", icon: "settings", group: "settings" },
  ],
};

export const fallbackEntities: EntitiesResponse = {
  agents: [
    {
      id: "hr-agent",
      name: "HR Assistant",
      kind: "agent",
      description: "Employee services, leave, payroll, and talent workflows.",
      tags: ["HR", "POLICY", "MEMORY"],
      stats: [],
      actions: ["chat", "config"],
    },
    {
      id: "it-agent",
      name: "IT Assistant",
      kind: "agent",
      description: "Tickets, assets, access requests, and support operations.",
      tags: ["IT", "ASSETS", "SUPPORT"],
      stats: [],
      actions: ["chat", "config"],
    },
    {
      id: "finance-agent",
      name: "Finance Assistant",
      kind: "agent",
      description: "Reimbursement, budget, invoices, and financial summaries.",
      tags: ["FINANCE", "APPROVALS"],
      stats: [],
      actions: ["chat", "config"],
    },
  ],
  teams: [
    {
      id: "router-team",
      name: "Router Team",
      kind: "team",
      description: "Coordinates HR, IT, Admin, Finance, and Legal assistants.",
      tags: ["COORDINATE", "MULTI-AGENT"],
      stats: [],
      actions: ["chat", "config"],
    },
    {
      id: "operations-team",
      name: "Operations Team",
      kind: "team",
      description: "Handles cross-domain employee operations and approvals.",
      tags: ["WORKFLOW", "HITL"],
      stats: [],
      actions: ["chat", "config"],
    },
    {
      id: "clinic-team",
      name: "Employee Clinic",
      kind: "team",
      description: "Answers benefits, wellness, and workplace-service questions with scoped records.",
      tags: ["CONTEXT-PROVIDER", "KNOWLEDGE-FILTER", "FALLBACK"],
      stats: [],
      actions: ["chat", "config"],
    },
  ],
  workflows: [
    {
      id: "onboarding",
      name: "Employee Onboarding",
      kind: "workflow",
      description: "Guides HR, IT, admin, and finance steps for new hires.",
      tags: ["PARALLEL", "CHECKLIST"],
      stats: [],
      actions: ["chat", "config"],
    },
    {
      id: "expense-review",
      name: "Expense Review",
      kind: "workflow",
      description: "Routes reimbursement checks and finance approvals.",
      tags: ["APPROVALS", "AUDIT"],
      stats: [],
      actions: ["chat", "config"],
    },
    {
      id: "daily-briefing",
      name: "Daily Briefing",
      kind: "workflow",
      description: "Scans calendar, tickets, finance updates, and policy changes in parallel.",
      tags: ["PARALLEL", "SCHEDULED", "BRIEFING"],
      stats: [],
      actions: ["chat", "config"],
    },
  ],
  interfaces: [
    {
      id: "chat",
      name: "Chat",
      kind: "interface",
      description: "/chat",
      tags: ["CHAT"],
      stats: [],
      actions: ["chat"],
    },
    {
      id: "api",
      name: "API",
      kind: "interface",
      description: "/v1/chat",
      tags: ["HTTP"],
      stats: [],
      actions: ["config"],
    },
  ],
  operating_systems: [
    {
      id: "mx-agent",
      name: "MX AgentOS",
      kind: "os",
      description: "Local production workspace",
      tags: ["CURRENT"],
      stats: ["5 AGENTS", "2 TEAMS", "2 WORKFLOWS"],
      actions: ["edit", "delete"],
    },
  ],
};

const table = (
  title: string,
  tableName: string,
  columns: Array<[string, string]>,
  rows: Record<string, unknown>[],
): TableResponse => ({
  title,
  database: "mx-agent-db",
  table: tableName,
  columns: columns.map(([key, label]) => ({
    key,
    label,
    mono: ["agent_id", "cron", "endpoint", "status", "trace_id"].includes(key),
  })),
  rows,
  filters: ["View: All"],
});

export const fallbackTables = {
  sessions: table("Sessions", "agno_sessions", [["name", "SESSION NAME"], ["updated_at", "UPDATED AT"]], [
    { id: "s-1", name: "新员工入职需要哪些步骤？", updated_at: "19 Jun 2026, 09:30" },
    { id: "s-2", name: "报销申请状态查询", updated_at: "18 Jun 2026, 16:12" },
    { id: "s-3", name: "VPN 无法连接", updated_at: "18 Jun 2026, 10:04" },
  ]),
  traces: table(
    "Traces",
    "agno_traces",
    [
      ["name", "NAME"],
      ["trace_id", "TRACE ID"],
      ["status", "STATUS"],
      ["duration", "DURATION"],
      ["spans", "SPANS"],
      ["agent_id", "AGENT ID"],
      ["input", "INPUT"],
      ["created_at", "CREATED AT"],
    ],
    [
      {
        id: "t-1",
        name: "RouterTeam.arun",
        trace_id: "9c645fe9dc507efba986d9f6e369b827",
        status: "OK",
        duration: "4.93s",
        spans: 18,
        agent_id: "router-team",
        input: "我要办理入职",
        run_id: "af2bbb00-71ed-452b-aef2-3dfad4930462",
        session_id: "1534cf8b-ec92-40e3-91ed-2fb1e942267c",
        user_id: "operator@mx.local",
        created_at: "19 Jun 2026, 09:31",
      },
      {
        id: "t-2",
        name: "FinanceAgent.arun",
        trace_id: "7a234cd5ab123cdef789012345abcdef",
        status: "OK",
        duration: "2.15s",
        spans: 6,
        agent_id: "finance-agent",
        input: "查询报销",
        run_id: "run-finance-20260618",
        session_id: "finance-session-20260618",
        user_id: "operator@mx.local",
        created_at: "18 Jun 2026, 16:13",
      },
      {
        id: "t-3",
        name: "ITAgent.ticket_triage",
        trace_id: "ef789abc12def345678901234567cdef",
        status: "ERROR",
        duration: "6.78s",
        spans: 8,
        agent_id: "it-agent",
        input: "VPN 无法连接",
        run_id: "run-it-20260618",
        session_id: "it-session-20260618",
        user_id: "operator@mx.local",
        created_at: "18 Jun 2026, 10:04",
      },
    ],
  ),
  memory: table("Memory", "agno_memories", [["content", "CONTENT"], ["topics", "TOPICS"], ["updated_at", "UPDATED AT"]], [
    {
      id: "m-1",
      content: "User prefers email notifications for project updates.",
      topics: ["PREFERENCES", "EMAIL"],
      updated_at: "15 Jan 2026, 14:16",
    },
    {
      id: "m-2",
      content: "Manager role can approve team leave requests.",
      topics: ["HR", "APPROVALS"],
      updated_at: "14 Jan 2026, 10:30",
    },
  ]),
  knowledge: table(
    "Knowledge",
    "agno_knowledge",
    [
      ["name", "NAME"],
      ["content_type", "CONTENT TYPE"],
      ["metadata", "METADATA"],
      ["status", "STATUS"],
      ["updated_at", "UPDATED AT"],
    ],
    [
      {
        id: "k-1",
        name: "employee-handbook",
        content_type: "File",
        metadata: { DOC_TYPE: "POLICY" },
        status: "COMPLETED",
        updated_at: "18 Jun 2026, 09:27",
      },
      {
        id: "k-2",
        name: "finance-policy",
        content_type: "File",
        metadata: { DOC_TYPE: "FINANCE" },
        status: "COMPLETED",
        updated_at: "18 Jun 2026, 09:20",
      },
    ],
  ),
  evaluations: table(
    "Evaluation",
    "agno_eval_runs",
    [["name", "EVALUATION NAME"], ["target", "AGENT/TEAM"], ["model", "MODEL"], ["type", "TYPE"], ["updated_at", "UPDATED AT"]],
    [{ id: "e-1", name: "router-smoke", target: "router-team", model: "glm-4-plus", type: "acceptance", updated_at: "19 Jun 2026, 08:00" }],
  ),
  approvals: table(
    "Approvals",
    "agno_approvals",
    [["action", "ACTION"], ["target", "AGENT/TEAM"], ["created_at", "CREATED AT"], ["params", "PARAMS"]],
    [{ id: "a-1", action: "approve_leave", target: "HR Assistant", created_at: "19 Jun 2026", params: { employee: "MX0001", days: 1 } }],
  ),
  schedules: table(
    "Scheduler",
    "agno_schedules",
    [["enabled", "ENABLED"], ["name", "NAME"], ["cron", "CRON"], ["endpoint", "ENDPOINT"], ["next_run", "NEXT RUN"], ["updated_at", "UPDATED AT"]],
    [
      {
        id: "sc-1",
        enabled: true,
        name: "Daily Summary Report",
        cron: "0 9 * * *",
        endpoint: "/v1/agents/summary/runs",
        next_run: "20 Jun 2026, 09:00 UTC",
        updated_at: "19 Jun 2026, 08:10",
      },
      {
        id: "sc-2",
        enabled: false,
        name: "Weekly Backup",
        cron: "0 4 * * 0",
        endpoint: "/v1/agents/backup/runs",
        next_run: "23 Jun 2026, 04:00 UTC",
        updated_at: "18 Jun 2026, 17:25",
      },
      {
        id: "sc-3",
        enabled: true,
        name: "Quarterly Compliance Audit",
        cron: "0 6 1 1,4,7,10 *",
        endpoint: "/v1/agents/compliance/runs",
        next_run: "1 Jul 2026, 06:00 UTC",
        updated_at: "16 Jun 2026, 11:42",
      },
      {
        id: "sc-4",
        enabled: false,
        name: "Daily Customer Feedback Digest",
        cron: "0 8 * * *",
        endpoint: "/v1/agents/feedback-digest/runs",
        next_run: "20 Jun 2026, 08:00 UTC",
        updated_at: "-",
      },
    ],
  ),
} satisfies Record<string, TableResponse>;

export const fallbackMetrics: MetricsResponse = {
  period: "JUN 2026",
  metrics: [
    { label: "Total tokens", value: "317.2K", points: [4, 9, 12, 8, 14].map((value, index) => ({ label: String(index + 1), value })) },
    { label: "Users", value: "35", points: [2, 4, 6, 9, 11].map((value, index) => ({ label: String(index + 1), value })) },
    { label: "Agent Runs", value: "170", points: [5, 8, 15, 12, 18].map((value, index) => ({ label: String(index + 1), value })) },
    { label: "Team Runs", value: "264", points: [7, 11, 9, 15, 21].map((value, index) => ({ label: String(index + 1), value })) },
  ],
  model_runs: [
    { model: "glm-4-plus", share: "54%" },
    { model: "gpt-4o", share: "26%" },
    { model: "others", share: "20%" },
  ],
  gated_message: "Detailed cost analytics will be connected in a later phase.",
};

export const fallbackSettings: SettingsResponse = {
  profile: { name: "MX Operator", username: "mx-operator", email: "operator@mx.local" },
  organization: { name: "MX Agent", members: 1, pending_invites: 0 },
  os: {
    name: "MX AgentOS",
    id: "mx-agent",
    endpoint_url: "http://localhost:8000",
    authorization: "jwt",
    tags: ["LOCAL", "PRODUCTION"],
  },
  billing: { tier: "Local", status: "self-hosted" },
};
